# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14071TwDs_y2Du-cmhJxhWq4akK4G3cvt
"""

input_scores = input("Enter scores separated by space: ")

scores = [int(s) for s in input_scores.split()]

fail_count = len([score for score in scores if score < 60])

print(fail_count)

